# Generated by Django 5.2.4 on 2025-12-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_address_user_gender_user_phone_user_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
