# Generated by Django 5.2.4 on 2025-12-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('adhd', 'ADHD'), ('depression', 'DEPRESSION'), ('anxiety', 'ANXIETY'), ('general', 'General Mental Health')], max_length=20),
        ),
    ]
