# Generated by Django 5.2.4 on 2025-12-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
    ]
