# Generated by Django 5.2.4 on 2025-12-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
