# Generated by Django 5.2.4 on 2026-03-09 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_booking_booked_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('adhd', 'ADHD Assessment'), ('anxiety', 'Anxiety Assessment')], max_length=20)),
                ('result', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.user')),
            ],
        ),
    ]
