# Generated by Django 5.2.4 on 2026-03-10 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assessmentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text="Doctor's diagnosis")),
                ('medications', models.JSONField(default=list, help_text='List of medications with dosage, frequency, duration')),
                ('notes', models.TextField(blank=True, help_text='Additional instructions', null=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='Recommended follow-up date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.booking')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.user')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
