# Generated by Django 5.2.4 on 2026-03-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='is_booked',
        ),
    ]
