# Generated by Django 5.2.4 on 2026-03-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_timeslot_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='max_patients',
            field=models.IntegerField(default=4),
        ),
    ]
